version: 0.0
os: linux
files:
  - source: /
    destination: C:\Users\Administrator\Desktop\visual--Dotnetapplication
hooks:
    ApplicationStop:
      - location: /codedeploy/deploy-scripts/application_stop.sh
        timeout: 10
    BeforeInstall:
      - location: /codedeploy/deploy-scripts/before-install.sh
        timeout: 10
    ApplicationStart:
      - location: /codedeploy/deploy-scripts/application_start.sh
        timeout: 10
