version: 0.2
phases:
  pre_build:
    commands:
      - cd src/.
      - echo Restore started on `date`
      - dotnet restore  visual--Dotnetapplication
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output visual--Dotnetapplication
artifacts:
  files:
    - '**/*'
    - codedeploy/deploy-scripts/**
    - appspec.yml
