version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore  WebApplication143.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output WebApplication143.csproj
artifacts:
  files:
    - '**/*'
    - codedeploy/deploy-scripts/**
    - appspec.yml
